# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Ben Holmgren
# Description of the Site
description: Math and Mountains
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://benholmgren.github.io/personal-site/assets/images/bg.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: bholmgren3@gmail.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  benholmgren
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: bholmgren3

# Google Analytics
google-analytics:  

# Disqus
disqus-shortname: benholmgren

# Name of the Author
author-name: benholmgren
# URL for the Image of the Author
author-image: https://benholmgren.github.io/personal-site/assets/images/profile
# 60 Words About the Author
author-about: Ben Holmgren is a researcher from Bozeman, Montana working at the intersection of mathematics and computer science. 
He is particularly interested in the algorithmic study of topology and geometry, and their diverse applications.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/benholmgren

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
